[project]
id = "cellar"
version = "0.1.0"
src = "src"
dep = "dep"
target = "native"
out   = "out/{target}/{profile}/bin/{name}{ext}"
obj   = "out/{target}/{profile}/obj"
ir    = "out/{target}/{profile}/ir"
asm   = "out/{target}/{profile}/asm"
tests = "out/{target}/{profile}/test/{name}"

[target.linux]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.windows]
isa = "x86_64"
os  = "windows"
abi = "win64"
ext = ".exe"

[target.darwin]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

[bin.cellar]
entry = "main.mach"

[profile.debug]
opt = 0

[profile.release]
opt = 2

[deps.mach-std]
git = "https://github.com/octalide/mach-std"
ref = "branch/main"

[deps.mach-glfw]
path = "../mach-glfw"

[deps.mach-gl]
path = "../mach-gl"

[deps.blit]
path = "../blit"
