[project]
id = "cellar"
version = "0.2.1"
mach = "^6.7"
src = "src"
out = "out/{target.name}/{profile.name}"

[target.linux-x86_64]
default = true
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.windows-x86_64]
isa = "x86_64"
os  = "windows"
abi = "win64"

[target.darwin-x86_64]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

[target.darwin-aarch64]
isa = "aarch64"
os  = "darwin"
abi = "aapcs64"

[profile.debug]
default = true
opt = 0
debug = true
simd = "scalarize"
vectorize = false
float_reassoc = false

[profile.release]
opt = 2
debug = false
simd = "scalarize"
vectorize = false
float_reassoc = false

[artifact.cellar]
default = true
kind = "bin"
entry = "bin/cellar.mach"
out = "bin/cellar{artifact.suffix}"
targets = ["*"]
link = []
need = []

[dep.std]
git = "https://github.com/briar-systems/mach-std"
version = "^9.4.1"

[dep.boom]
git = "https://github.com/briar-systems/boom"
version = "^0.33.0"

[dep.blit]
git = "https://github.com/briar-systems/blit"
version = "^0.8.0"
